### ISSUE TITLE
Tracking issue for page's contents

### ISSUE THREAD

**Issue by juchiast** [nmcntt2-cntn2016/project1-name#3]
Chỉnh text của trang đi các bạn 🇻🇪 

- [x] "Bạn nộp đơn như thế nào?" => "Bạn ĐANG nộp đơn như thế nào?"
- [ ] "Cách hoạt động của hệ thống" thay hình này = "CachThucHoatDong.png"
- [x] "Phương thức để sinh viên và các phòng ban sử dụng hệ thống" => "Các chức năng"
- [x] Tốn nhiều thời gian, công sức => Tốn nhiều thời gian và công sức

**Comment by ltkhang** [comment]
"Bạn nộp đơn như thế nào?" => "Bạn ĐANG nộp đơn như thế nào?" nghe hợp lý hơn, vì vốn dĩ mình không cần câu trả lời của user mà là hỏi tu từ thôi

**Comment by ltkhang** [comment]
"Cách hoạt động của hệ thống" thay hình này = "CachThucHoatDong.png"

**Comment by ltkhang** [comment]
Đổi "Phương thức để sinh viên và các phòng ban sử dụng hệ thống" sang "Các chức năng"
Mỗi một người dùng của mình có chức năng riêng

**Comment by ltkhang** [comment]
Tốn nhiều thời gian, công sức => Tốn nhiều thời gian và công sức
